const exercises = [
    {
        id: 1,
        name: "Squat Jump",
        type: "explosive",
        sets: "3-5",
        reps: "3-5",
        difficulty: "beginner",
        flavor: "bilateral",
        description:
            "An explosive bodyweight movement starting in a squat position and jumping as high as possible.",
    },
    {
        id: 2,
        name: "Hang Jump Shrug",
        type: "explosive",
        sets: "3-5",
        reps: "3-5",
        difficulty: "beginner",
        flavor: "bilateral",
        description:
            "A power development exercise involving a jump and a shrug with a barbell or dumbbells, starting from a hanging position.",
    },
    {
        id: 3,
        name: "Clean Pull",
        type: "explosive",
        sets: "3-5",
        reps: "3-5",
        difficulty: "intermediate",
        flavor: "bilateral",
        description:
            "The pulling portion of the clean, focusing on explosive hip and leg drive to lift the bar.",
    },
    {
        id: 4,
        name: "Snatch Pull",
        type: "explosive",
        sets: "3-5",
        reps: "3-5",
        difficulty: "intermediate",
        flavor: "bilateral",
        description:
            "The pulling portion of the snatch, using a wide grip to lift the bar explosively from the floor.",
    },
    {
        id: 5,
        name: "Clean High Pull",
        type: "explosive",
        sets: "3-5",
        reps: "3-5",
        difficulty: "intermediate",
        flavor: "bilateral",
        description:
            "A clean pull with an added high pull, emphasizing upper body explosiveness.",
    },
    {
        id: 6,
        name: "Snatch High Pull",
        type: "explosive",
        sets: "3-5",
        reps: "3-5",
        difficulty: "advanced",
        flavor: "bilateral",
        description:
            "A snatch pull with an added high pull, requiring significant speed and coordination.",
    },
    {
        id: 7,
        name: "Hang Power Clean (dumbbell)",
        type: "explosive",
        sets: "3-5",
        reps: "3-5",
        difficulty: "intermediate",
        flavor: "unilateral",
        description:
            "A variation of the power clean starting from an above-the-knee 'hang' position.",
    },
    {
        id: 126,
        name: "Hang Power Clean (barbell)",
        type: "explosive",
        sets: "3-5",
        reps: "3-5",
        difficulty: "intermediate",
        flavor: "bilateral",
        description:
            "A variation of the power clean starting from an above-the-knee 'hang' position.",
    },
    {
        id: 8,
        name: "Power Clean (dumbbell)",
        type: "explosive",
        sets: "3-5",
        reps: "3-5",
        difficulty: "advanced",
        flavor: "unilateral",
        description:
            "An Olympic lift where the bar is explosively pulled from the floor and caught on the shoulders.",
    },
    {
        id: 127,
        name: "Power Clean (barbell)",
        type: "explosive",
        sets: "3-5",
        reps: "3-5",
        difficulty: "advanced",
        flavor: "bilateral",
        description:
            "An Olympic lift where the bar is explosively pulled from the floor and caught on the shoulders.",
    },
    {
        id: 9,
        name: "Hang Power Snatch (dumbbell)",
        type: "explosive",
        sets: "3-5",
        reps: "3-5",
        difficulty: "intermediate",
        flavor: "unilateral",
        description:
            "A variation of the power snatch starting from a 'hang' position.",
    },
    {
        id: 128,
        name: "Hang Power Snatch (barbell)",
        type: "explosive",
        sets: "3-5",
        reps: "3-5",
        difficulty: "intermediate",
        flavor: "bilateral",
        description:
            "A variation of the power snatch starting from a 'hang' position.",
    },
    {
        id: 10,
        name: "Muscle Snatch",
        type: "explosive",
        sets: "3-5",
        reps: "3-5",
        difficulty: "advanced",
        flavor: "bilateral",
        description:
            "A snatch variation that builds strength by muscling the bar overhead without a re-bend of the knees.",
    },
    {
        id: 11,
        name: "Power Snatch (barbell)",
        type: "explosive",
        sets: "3-5",
        reps: "3-5",
        difficulty: "advanced",
        flavor: "bilateral",
        description:
            "An Olympic lift where the bar is explosively pulled from the floor and caught overhead in one motion.",
    },
    {
        id: 129,
        name: "Power Snatch (dumbbell)",
        type: "explosive",
        sets: "3-5",
        reps: "3-5",
        difficulty: "advanced",
        flavor: "unilateral",
        description:
            "An Olympic lift where the bar is explosively pulled from the floor and caught overhead in one motion.",
    },
    {
        id: 12,
        name: "Narrow-Grip Power Snatch",
        type: "explosive",
        sets: "3-5",
        reps: "3-5",
        difficulty: "advanced",
        flavor: "bilateral",
        description:
            "A snatch performed with a closer grip, challenging shoulder mobility and strength.",
    },
    {
        id: 13,
        name: "One-Arm Dumbbell Snatch",
        type: "explosive",
        sets: "3-5",
        reps: "3-5",
        difficulty: "intermediate",
        flavor: "unilateral",
        description:
            "A unilateral explosive movement lifting a dumbbell from the floor to an overhead position.",
    },
    {
        id: 14,
        name: "Front Squat",
        type: "knee-dominant",
        sets: "3-4",
        reps: "6-12",
        difficulty: "intermediate",
        flavor: "bilateral",
        description:
            "A squat variation with the barbell resting across the front of the shoulders, emphasizing quad and core strength.",
    },
    {
        id: 15,
        name: "Back Squat",
        type: "knee-dominant",
        sets: "3-4",
        reps: "6-12",
        difficulty: "beginner",
        flavor: "bilateral",
        description:
            "A fundamental strength exercise where a barbell is placed on the upper back to perform a squat.",
    },
    {
        id: 16,
        name: "Overhead Squat",
        type: "knee-dominant",
        sets: "3-4",
        reps: "6-12",
        difficulty: "advanced",
        flavor: "bilateral",
        description:
            "A squat performed while holding a barbell overhead, requiring exceptional mobility and stability.",
    },
    {
        id: 17,
        name: "Split Squat",
        type: "knee-dominant",
        sets: "3-4",
        reps: "6-12",
        difficulty: "beginner",
        flavor: "unilateral",
        description:
            "A stationary lunge (no stepping forward) that builds unilateral leg strength and stability.",
    },
    {
        id: 18,
        name: "Side Squat",
        type: "knee-dominant",
        sets: "3-4",
        reps: "6-12",
        difficulty: "beginner",
        flavor: "bilateral",
        description:
            "A squat performed by stepping to the side, targeting inner and outer thighs.",
    },
    {
        id: 19,
        name: "Clean-Grip Deadlift",
        type: "knee-dominant",
        sets: "3-4",
        reps: "6-12",
        difficulty: "intermediate",
        flavor: "bilateral",
        description:
            "A deadlift using the same grip and stance as a clean, focusing on leg drive.",
    },
    {
        id: 20,
        name: "Forward Lunge",
        type: "knee-dominant",
        sets: "3-4",
        reps: "6-12",
        difficulty: "beginner",
        flavor: "unilateral",
        description:
            "A classic lunge variation stepping forward to challenge balance and leg strength.",
    },
    {
        id: 21,
        name: "Reverse Lunge",
        type: "knee-dominant",
        sets: "3-4",
        reps: "6-12",
        difficulty: "beginner",
        flavor: "unilateral",
        description:
            "A lunge variation stepping backward, often easier on the knees than a forward lunge.",
    },
    {
        id: 22,
        name: "Side Lunge",
        type: "knee-dominant",
        sets: "3-4",
        reps: "6-12",
        difficulty: "beginner",
        flavor: "unilateral",
        description:
            "A lateral movement that builds strength and flexibility in the frontal plane.",
    },
    {
        id: 23,
        name: "Drop Lunge",
        type: "knee-dominant",
        sets: "3-4",
        reps: "6-12",
        difficulty: "intermediate",
        flavor: "unilateral",
        description:
            "A lunge variation where the back leg crosses behind the front leg, targeting the glutes.",
    },
    {
        id: 24,
        name: "Stepup",
        type: "knee-dominant",
        sets: "3-4",
        reps: "6-12",
        difficulty: "beginner",
        flavor: "unilateral",
        description:
            "A simple yet effective exercise, stepping up onto a bench or box.",
    },
    {
        id: 25,
        name: "Lateral Stepup",
        type: "knee-dominant",
        sets: "3-4",
        reps: "6-12",
        difficulty: "intermediate",
        flavor: "unilateral",
        description:
            "A step-up performed from the side of the box, emphasizing hip stability.",
    },
    {
        id: 26,
        name: "Bulgarian Split Squat",
        type: "knee-dominant",
        sets: "3-4",
        reps: "6-12",
        difficulty: "intermediate",
        flavor: "unilateral",
        description:
            "A challenging split squat with the rear foot elevated on a bench.",
    },
    {
        id: 27,
        name: "Bulgarian Split Deadlift",
        type: "knee-dominant",
        sets: "3-4",
        reps: "6-12",
        difficulty: "intermediate",
        flavor: "unilateral",
        description:
            "A single-leg deadlift variation with the rear foot elevated.",
    },
    {
        id: 28,
        name: "Single-Leg Bench Getup",
        type: "knee-dominant",
        sets: "3-4",
        reps: "6-12",
        difficulty: "intermediate",
        flavor: "unilateral",
        description:
            "An advanced movement requiring balance and strength to stand up from a bench on one leg.",
    },
    {
        id: 29,
        name: "Crouching Single-Leg Squat",
        type: "knee-dominant",
        sets: "3-4",
        reps: "6-12",
        difficulty: "advanced",
        flavor: "unilateral",
        description: "A partial single-leg squat from a crouched position.",
    },
    {
        id: 30,
        name: "Partial Single-Leg Squat (Bench/Box)",
        type: "knee-dominant",
        sets: "3-4",
        reps: "6-12",
        difficulty: "intermediate",
        flavor: "unilateral",
        description:
            "A pistol squat progression, squatting down to touch a bench or box.",
    },
    {
        id: 31,
        name: "Partial Single-Leg Squat (Standing on Bench)",
        type: "knee-dominant",
        sets: "3-4",
        reps: "6-12",
        difficulty: "advanced",
        flavor: "unilateral",
        description:
            "A single-leg squat performed while standing on a bench to increase range of motion.",
    },
    {
        id: 32,
        name: "Full Pistol Squat",
        type: "knee-dominant",
        sets: "3-4",
        reps: "6-12",
        difficulty: "advanced",
        flavor: "unilateral",
        description:
            "The full single-leg squat, a master-level bodyweight exercise.",
    },
    {
        id: 33,
        name: "Good Morning",
        type: "hip-dominant",
        sets: "3-4",
        reps: "8-15",
        difficulty: "intermediate",
        flavor: "bilateral",
        description:
            "A posterior chain exercise where you hinge at the hips with a barbell on your back.",
    },
    {
        id: 34,
        name: "Seated Good Morning",
        type: "hip-dominant",
        sets: "3-4",
        reps: "8-15",
        difficulty: "intermediate",
        flavor: "bilateral",
        description:
            "A variation of the Good Morning performed while seated to isolate the lower back.",
    },
    {
        id: 35,
        name: "Zercher Good Morning",
        type: "hip-dominant",
        sets: "3-4",
        reps: "8-15",
        difficulty: "advanced",
        flavor: "bilateral",
        description:
            "A Good Morning performed with the barbell held in the crook of the elbows.",
    },
    {
        id: 36,
        name: "Romanian Deadlift",
        type: "hip-dominant",
        sets: "3-4",
        reps: "8-15",
        difficulty: "beginner",
        flavor: "bilateral",
        description:
            "A deadlift variation with minimal knee bend, focusing on the hamstrings and glutes.",
    },
    {
        id: 37,
        name: "Back Extension",
        type: "hip-dominant",
        sets: "3-4",
        reps: "8-15",
        difficulty: "beginner",
        flavor: "bilateral",
        description:
            "An exercise to strengthen the lower back, usually performed on a hyperextension bench.",
    },
    {
        id: 38,
        name: "Supine Hip Extension",
        type: "hip-dominant",
        sets: "3-4",
        reps: "8-15",
        difficulty: "beginner",
        flavor: "bilateral",
        description:
            "Also known as a glute bridge, this exercise targets the glutes and hamstrings.",
    },
    {
        id: 39,
        name: "Swiss Ball Glute-Hamstring",
        type: "hip-dominant",
        sets: "3-4",
        reps: "8-15",
        difficulty: "intermediate",
        flavor: "bilateral",
        description:
            "A challenging exercise on a Swiss ball that combines a leg curl and a hip bridge.",
    },
    {
        id: 40,
        name: "Reverse Hyperextension",
        type: "hip-dominant",
        sets: "3-4",
        reps: "8-15",
        difficulty: "intermediate",
        flavor: "bilateral",
        description:
            "An exercise performed on a dedicated machine to target the glutes and lower back.",
    },
    {
        id: 41,
        name: "Single-Leg Good Morning",
        type: "hip-dominant",
        sets: "3-4",
        reps: "8-15",
        difficulty: "advanced",
        flavor: "unilateral",
        description:
            "A Good Morning performed on one leg, demanding high levels of balance and stability.",
    },
    {
        id: 42,
        name: "Split Good Morning",
        type: "hip-dominant",
        sets: "3-4",
        reps: "8-15",
        difficulty: "intermediate",
        flavor: "unilateral",
        description:
            "A Good Morning performed in a split stance for unilateral focus.",
    },
    {
        id: 43,
        name: "Single-Leg Romanian Deadlift",
        type: "hip-dominant",
        sets: "3-4",
        reps: "8-15",
        difficulty: "intermediate",
        flavor: "unilateral",
        description:
            "A unilateral RDL that builds balance, stability, and hamstring strength.",
    },
    {
        id: 44,
        name: "Single-Leg Back Extension",
        type: "hip-dominant",
        sets: "3-4",
        reps: "8-15",
        difficulty: "intermediate",
        flavor: "unilateral",
        description:
            "A back extension performed with one leg, increasing the challenge.",
    },
    {
        id: 45,
        name: "Single-Leg Supine Hip Extension",
        type: "hip-dominant",
        sets: "3-4",
        reps: "8-15",
        difficulty: "beginner",
        flavor: "unilateral",
        description:
            "A glute bridge performed on one leg to increase intensity.",
    },
    {
        id: 46,
        name: "Single-Leg Swiss Ball Glute-Hamstring",
        type: "hip-dominant",
        sets: "3-4",
        reps: "8-15",
        difficulty: "advanced",
        flavor: "unilateral",
        description:
            "From a lying position, put one foot on a Swiss ball with a bent knee and thrust your hips upward with the other foot elevated and unused.",
    },
    {
        id: 47,
        name: "Bench Press",
        type: "horizontal-push",
        sets: "3-4",
        reps: "6-12",
        difficulty: "beginner",
        flavor: "bilateral",
        description:
            "The classic upper body lift, pressing a barbell from the chest while lying on a bench.",
    },
    {
        id: 48,
        name: "Incline Bench Press",
        type: "horizontal-push",
        sets: "3-4",
        reps: "6-12",
        difficulty: "beginner",
        flavor: "bilateral",
        description:
            "A bench press on an inclined bench to target the upper chest and shoulders.",
    },
    {
        id: 49,
        name: "Close-Grip Bench Press",
        type: "horizontal-push",
        sets: "3-4",
        reps: "6-12",
        difficulty: "intermediate",
        flavor: "bilateral",
        description:
            "A bench press with a narrower grip to place more emphasis on the triceps.",
    },
    {
        id: 50,
        name: "Close-Grip Incline Press",
        type: "horizontal-push",
        sets: "3-4",
        reps: "6-12",
        difficulty: "intermediate",
        flavor: "bilateral",
        description: "A close-grip press on an incline bench.",
    },
    {
        id: 51,
        name: "Reverse-Grip Bench Press",
        type: "horizontal-push",
        sets: "3-4",
        reps: "6-12",
        difficulty: "advanced",
        flavor: "bilateral",
        description: "A bench press using a supinated (underhand) grip.",
    },
    {
        id: 52,
        name: "Pushup (floor, ball, chair)",
        type: "horizontal-push",
        sets: "3-4",
        reps: "To failure",
        difficulty: "beginner",
        flavor: "bilateral",
        description:
            "The fundamental bodyweight pressing exercise, can be modified for difficulty.",
    },
    {
        id: 53,
        name: "Dip",
        type: "horizontal-push",
        sets: "3-4",
        reps: "6-12",
        difficulty: "intermediate",
        flavor: "bilateral",
        description:
            "A bodyweight or weighted exercise on parallel bars that targets the chest and triceps.",
    },
    {
        id: 54,
        name: "Dumbbell Bench Press",
        type: "horizontal-push",
        sets: "3-4",
        reps: "6-12",
        difficulty: "beginner",
        flavor: "bilateral",
        description:
            "A bench press using dumbbells, which allows for greater range of motion and stabilization.",
    },
    {
        id: 55,
        name: "Dumbbell Incline Bench Press",
        type: "horizontal-push",
        sets: "3-4",
        reps: "6-12",
        difficulty: "beginner",
        flavor: "bilateral",
        description: "An incline press using dumbbells.",
    },
    {
        id: 56,
        name: "Dumbbell Alternating Bench Press",
        type: "horizontal-push",
        sets: "3-4",
        reps: "6-12",
        difficulty: "intermediate",
        flavor: "unilateral",
        description: "A dumbbell press where you press one arm at a time.",
    },
    {
        id: 57,
        name: "One-Arm Dumbbell Bench Press",
        type: "horizontal-push",
        sets: "3-4",
        reps: "6-12",
        difficulty: "intermediate",
        flavor: "unilateral",
        description:
            "A dumbbell press using only one arm, heavily engaging the core.",
    },
    {
        id: 58,
        name: "One-Arm Dumbbell Incline Bench Press",
        type: "horizontal-push",
        sets: "3-4",
        reps: "6-12",
        difficulty: "intermediate",
        flavor: "unilateral",
        description: "A one-arm press on an incline.",
    },
    {
        id: 59,
        name: "Side-to-Side Pushup",
        type: "horizontal-push",
        sets: "3-4",
        reps: "To failure",
        difficulty: "intermediate",
        flavor: "unilateral",
        description:
            "A pushup where you shift your weight from one side to the other.",
    },
    {
        id: 60,
        name: "Standing Cable Chest Press",
        type: "horizontal-push",
        sets: "3-4",
        reps: "8-15",
        difficulty: "beginner",
        flavor: "bilateral",
        description:
            "A press using a cable machine, providing constant tension.",
    },
    {
        id: 61,
        name: "Bent-Over Row",
        type: "horizontal-pull",
        sets: "3-4",
        reps: "8-12",
        difficulty: "beginner",
        flavor: "bilateral",
        description:
            "A classic back-building exercise, pulling a barbell towards the torso from a hinged position.",
    },
    {
        id: 62,
        name: "Modified T-Bar Row",
        type: "horizontal-pull",
        sets: "3-4",
        reps: "8-12",
        difficulty: "beginner",
        flavor: "bilateral",
        description:
            "A rowing variation using a T-bar machine or a barbell wedged into a corner.",
    },
    {
        id: 63,
        name: "Horizontal Pullup",
        type: "horizontal-pull",
        sets: "3-4",
        reps: "8-12",
        difficulty: "intermediate",
        flavor: "bilateral",
        description:
            "Also known as an inverted row, this is a bodyweight pulling exercise.",
    },
    {
        id: 64,
        name: "Standing Cable Row to Ribcage",
        type: "horizontal-pull",
        sets: "3-4",
        reps: "8-12",
        difficulty: "beginner",
        flavor: "bilateral",
        description: "A row performed with a cable machine while standing.",
    },
    {
        id: 65,
        name: "Standing Cable Row to Neck",
        type: "horizontal-pull",
        sets: "3-4",
        reps: "8-12",
        difficulty: "intermediate",
        flavor: "bilateral",
        description:
            "A high row variation to target the upper back and rear delts.",
    },
    {
        id: 66,
        name: "Cable Face Pull",
        type: "horizontal-pull",
        sets: "3-4",
        reps: "10-15",
        difficulty: "beginner",
        flavor: "bilateral",
        description:
            "An excellent exercise for shoulder health and upper back strength.",
    },
    {
        id: 67,
        name: "Bent-Over Dumbbell Alternating Row",
        type: "horizontal-pull",
        sets: "3-4",
        reps: "8-12",
        difficulty: "beginner",
        flavor: "unilateral",
        description:
            "A bent-over row with dumbbells, pulling one arm at a time.",
    },
    {
        id: 68,
        name: "Bent-Over Two-Point Dumbbell Row",
        type: "horizontal-pull",
        sets: "3-4",
        reps: "8-12",
        difficulty: "beginner",
        flavor: "bilateral",
        description:
            "A dumbbell row where both dumbbells are pulled simultaneously.",
    },
    {
        id: 69,
        name: "Three-Point Dumbbell Row with Twist",
        type: "horizontal-pull",
        sets: "3-4",
        reps: "8-12",
        difficulty: "intermediate",
        flavor: "unilateral",
        description:
            "A single-arm dumbbell row with a supportive hand on a bench, adding a torso twist.",
    },
    {
        id: 70,
        name: "One-Arm Standing Cable Row",
        type: "horizontal-pull",
        sets: "3-4",
        reps: "8-12",
        difficulty: "beginner",
        flavor: "unilateral",
        description: "A unilateral standing row using a cable machine.",
    },
    {
        id: 71,
        name: "Horizontal Side-to-Side Pullup",
        type: "horizontal-pull",
        sets: "3-4",
        reps: "8-12",
        difficulty: "advanced",
        flavor: "unilateral",
        description:
            "An advanced inverted row where you pull your body towards one hand at a time.",
    },
    {
        id: 72,
        name: "One-Arm Horizontal Pullup",
        type: "horizontal-pull",
        sets: "3-4",
        reps: "8-12",
        difficulty: "advanced",
        flavor: "unilateral",
        description: "An inverted row performed with only one arm.",
    },
    {
        id: 73,
        name: "Shoulder Press",
        type: "vertical-push",
        sets: "3-4",
        reps: "6-12",
        difficulty: "beginner",
        flavor: "bilateral",
        description:
            "A classic overhead press with a barbell to build shoulder strength.",
    },
    {
        id: 74,
        name: "Push Press",
        type: "vertical-push",
        sets: "3-4",
        reps: "6-12",
        difficulty: "intermediate",
        flavor: "bilateral",
        description:
            "An overhead press that uses leg drive to help initiate the movement.",
    },
    {
        id: 75,
        name: "Push Jerk",
        type: "vertical-push",
        sets: "3-4",
        reps: "6-12",
        difficulty: "advanced",
        flavor: "bilateral",
        description:
            "An explosive overhead lift where you dip under the bar to catch it.",
    },
    {
        id: 76,
        name: "Split Jerk",
        type: "vertical-push",
        sets: "3-4",
        reps: "6-12",
        difficulty: "advanced",
        flavor: "unilateral",
        description:
            "An explosive overhead lift where you catch the bar in a split stance.",
    },
    {
        id: 77,
        name: "Jackknife Pushup",
        type: "vertical-push",
        sets: "3-4",
        reps: "6-12",
        difficulty: "intermediate",
        flavor: "bilateral",
        description:
            "A pushup with feet elevated, similar to a pike pushup, to target the shoulders.",
    },
    {
        id: 78,
        name: "Plate Raise + Truck Driver",
        type: "vertical-push",
        sets: "3-4",
        reps: "10-15",
        difficulty: "beginner",
        flavor: "bilateral",
        description:
            "A combination of a front plate raise and a rotational 'truck driver' movement.",
    },
    {
        id: 79,
        name: "Dumbbell Shoulder Press",
        type: "vertical-push",
        sets: "3-4",
        reps: "6-12",
        difficulty: "beginner",
        flavor: "bilateral",
        description:
            "An overhead press using dumbbells, often done seated for stability.",
    },
    {
        id: 80,
        name: "Dumbbell Push Press",
        type: "vertical-push",
        sets: "3-4",
        reps: "6-12",
        difficulty: "intermediate",
        flavor: "bilateral",
        description: "A push press using dumbbells.",
    },
    {
        id: 81,
        name: "Dumbbell Push Jerk",
        type: "vertical-push",
        sets: "3-4",
        reps: "6-12",
        difficulty: "advanced",
        flavor: "bilateral",
        description: "A push jerk using dumbbells.",
    },
    {
        id: 82,
        name: "Dumbbell Split Jerk",
        type: "vertical-push",
        sets: "3-4",
        reps: "6-12",
        difficulty: "advanced",
        flavor: "unilateral",
        description: "A split jerk using dumbbells.",
    },
    {
        id: 83,
        name: "Dumbbell One-Arm Press + Bend",
        type: "vertical-push",
        sets: "3-4",
        reps: "6-12",
        difficulty: "intermediate",
        flavor: "unilateral",
        description:
            "A one-arm press combined with a lateral bend to engage the obliques.",
    },
    {
        id: 84,
        name: "Dumbbell Alternating Press",
        type: "vertical-push",
        sets: "3-4",
        reps: "6-12",
        difficulty: "beginner",
        flavor: "unilateral",
        description:
            "An overhead press with dumbbells, pressing one arm at a time.",
    },
    {
        id: 85,
        name: "Supported Dumbbell One-Arm Press",
        type: "vertical-push",
        sets: "3-4",
        reps: "6-12",
        difficulty: "beginner",
        flavor: "unilateral",
        description:
            "A one-arm press performed while holding onto a stable object for support.",
    },
    {
        id: 86,
        name: "Side-to-Side Jackknife Pushup",
        type: "vertical-push",
        sets: "3-4",
        reps: "6-12",
        difficulty: "advanced",
        flavor: "unilateral",
        description:
            "A jackknife pushup where you shift your weight from side to side.",
    },
    {
        id: 87,
        name: "Dumbbell Parallel-Grip Push Press",
        type: "vertical-push",
        sets: "3-4",
        reps: "6-12",
        difficulty: "intermediate",
        flavor: "bilateral",
        description:
            "A push press with dumbbells held in a neutral (palms facing) grip.",
    },
    {
        id: 88,
        name: "Dumbbell Scaption",
        type: "vertical-push",
        sets: "3-4",
        reps: "10-15",
        difficulty: "beginner",
        flavor: "bilateral",
        description:
            "Raising dumbbells at a 30-45 degree angle in front of the body, in the scapular plane.",
    },
    {
        id: 89,
        name: "Dumbbell Scaption with Shrug",
        type: "vertical-push",
        sets: "3-4",
        reps: "10-15",
        difficulty: "beginner",
        flavor: "bilateral",
        description:
            "A scaption raise with an added shrug at the top of the movement.",
    },
    {
        id: 90,
        name: "Chinup",
        type: "vertical-pull",
        sets: "3-4",
        reps: "6-12",
        difficulty: "intermediate",
        flavor: "bilateral",
        description:
            "A pullup with a supinated (underhand) grip, emphasizing the biceps.",
    },
    {
        id: 91,
        name: "Pullup",
        type: "vertical-pull",
        sets: "3-4",
        reps: "6-12",
        difficulty: "intermediate",
        flavor: "bilateral",
        description:
            "A classic bodyweight exercise, pulling your body up with a pronated (overhand) grip.",
    },
    {
        id: 92,
        name: "Mixed-Grip Pullup",
        type: "vertical-pull",
        sets: "3-4",
        reps: "6-12",
        difficulty: "intermediate",
        flavor: "bilateral",
        description: "A pullup with one hand overhand and one hand underhand.",
    },
    {
        id: 93,
        name: "Lat Pulldown",
        type: "vertical-pull",
        sets: "3-4",
        reps: "8-12",
        difficulty: "beginner",
        flavor: "bilateral",
        description: "A machine-based exercise that mimics the pullup motion.",
    },
    {
        id: 94,
        name: "Parallel-Grip Pullup/Pulldown",
        type: "vertical-pull",
        sets: "3-4",
        reps: "8-12",
        difficulty: "beginner",
        flavor: "bilateral",
        description:
            "A pullup or pulldown using a neutral grip (palms facing each other).",
    },
    {
        id: 95,
        name: "Single-Arm Pullup",
        type: "vertical-pull",
        sets: "3-4",
        reps: "3-8",
        difficulty: "advanced",
        flavor: "unilateral",
        description:
            "An extremely advanced pullup variation performed with one arm.",
    },
    {
        id: 96,
        name: "Single-Arm Lat Pulldown",
        type: "vertical-pull",
        sets: "3-4",
        reps: "8-12",
        difficulty: "intermediate",
        flavor: "unilateral",
        description: "A lat pulldown performed one arm at a time.",
    },
    {
        id: 97,
        name: "Side-to-Side Pullup",
        type: "vertical-pull",
        sets: "3-4",
        reps: "6-12",
        difficulty: "advanced",
        flavor: "unilateral",
        description:
            "A pullup where you pull your body towards one hand, then the other.",
    },
    // Core exercises: most are bilateral unless specified
    {
        id: 98,
        name: "Seated Russian Twist",
        type: "core",
        sets: "3",
        reps: "10-15",
        difficulty: "beginner",
        flavor: "bilateral",
        description:
            "A core exercise that involves twisting the torso from side to side.",
    },
    {
        id: 99,
        name: "Corkscrew",
        type: "core",
        sets: "3",
        reps: "10-15",
        difficulty: "intermediate",
        flavor: "bilateral",
        description:
            "An advanced Pilates exercise for oblique and lower ab strength.",
    },
    {
        id: 100,
        name: "Swiss Ball Weight Roll",
        type: "core",
        sets: "3",
        reps: "10-15",
        difficulty: "intermediate",
        flavor: "bilateral",
        description: "Placeholder description.",
    },
    {
        id: 101,
        name: "Barbell Torque",
        type: "core",
        sets: "3",
        reps: "10-15",
        difficulty: "intermediate",
        flavor: "bilateral",
        description: "Placeholder description.",
    },
    {
        id: 102,
        name: "Windshield Wiper",
        type: "core",
        sets: "3",
        reps: "10-15",
        difficulty: "advanced",
        flavor: "bilateral",
        description:
            "Lying on your back, you rotate your legs from side to side like windshield wipers.",
    },
    {
        id: 103,
        name: "Cable Rotator",
        type: "core",
        sets: "3",
        reps: "10-15",
        difficulty: "beginner",
        flavor: "bilateral",
        description: "Placeholder description.",
    },
    {
        id: 104,
        name: "Cable Reverse Wood Chop",
        type: "core",
        sets: "3",
        reps: "10-15",
        difficulty: "beginner",
        flavor: "unilateral",
        description: "A wood chop variation from a low to high position.",
    },
    {
        id: 105,
        name: "Cable Wood Chop",
        type: "core",
        sets: "3",
        reps: "10-15",
        difficulty: "beginner",
        flavor: "unilateral",
        description:
            "A functional core exercise that mimics a chopping motion with a cable.",
    },
    {
        id: 106,
        name: "Cable Rotating Crunch",
        type: "core",
        sets: "3",
        reps: "10-15",
        difficulty: "intermediate",
        flavor: "bilateral",
        description: "A crunch with a rotational component using a cable.",
    },
    {
        id: 107,
        name: "Cable Rotating Extension",
        type: "core",
        sets: "3",
        reps: "10-15",
        difficulty: "intermediate",
        flavor: "bilateral",
        description: "Placeholder description.",
    },
    {
        id: 108,
        name: "Cable Push-Pull Rotation",
        type: "core",
        sets: "3",
        reps: "10-15",
        difficulty: "intermediate",
        flavor: "bilateral",
        description:
            "A rotational exercise using a push-pull motion with cables.",
    },
    {
        id: 109,
        name: "Medicine Ball Standing Wall Throw",
        type: "core",
        sets: "3",
        reps: "10-15",
        difficulty: "beginner",
        flavor: "bilateral",
        description:
            "Explosively throwing a medicine ball against a wall from a rotational stance.",
    },
    {
        id: 110,
        name: "Medicine Ball Over-the-Shoulder Throw",
        type: "core",
        sets: "3",
        reps: "10-15",
        difficulty: "intermediate",
        flavor: "bilateral",
        description: "Placeholder description.",
    },
    {
        id: 111,
        name: "Medicine Ball 1-2-3 Throw",
        type: "core",
        sets: "3",
        reps: "10-15",
        difficulty: "intermediate",
        flavor: "bilateral",
        description: "Placeholder description.",
    },
    {
        id: 112,
        name: "Four-Point Plank",
        type: "core",
        sets: "3",
        reps: "30-60s",
        difficulty: "beginner",
        flavor: "bilateral",
        description: "The standard plank exercise on both hands and feet.",
    },
    {
        id: 113,
        name: "Three-Point Plank",
        type: "core",
        sets: "3",
        reps: "30-60s",
        difficulty: "intermediate",
        flavor: "unilateral",
        description: "A plank performed while lifting one limb off the ground.",
    },
    {
        id: 114,
        name: "Two-Point Plank",
        type: "core",
        sets: "3",
        reps: "30-60s",
        difficulty: "advanced",
        flavor: "unilateral",
        description:
            "A highly challenging plank, lifting one arm and the opposite leg simultaneously.",
    },
    {
        id: 115,
        name: "Side Bridge",
        type: "core",
        sets: "3",
        reps: "30-60s",
        difficulty: "beginner",
        flavor: "unilateral",
        description: "Also known as a side plank, this targets the obliques.",
    },
    {
        id: 116,
        name: "Four-Point Supine Bridge",
        type: "core",
        sets: "3",
        reps: "30-60s",
        difficulty: "beginner",
        flavor: "bilateral",
        description: "Also known as a glute bridge.",
    },
    {
        id: 117,
        name: "Three-Point Supine Bridge",
        type: "core",
        sets: "3",
        reps: "30-60s",
        difficulty: "intermediate",
        flavor: "unilateral",
        description: "A glute bridge performed with one leg extended.",
    },
    {
        id: 118,
        name: "Dynamic Plank",
        type: "core",
        sets: "3",
        reps: "30-60s",
        difficulty: "intermediate",
        flavor: "bilateral",
        description: "Placeholder description.",
    },
    {
        id: 119,
        name: "Plank with Elbow to Knee",
        type: "core",
        sets: "3",
        reps: "30-60s",
        difficulty: "intermediate",
        flavor: "unilateral",
        description:
            "From a plank position, bringing one knee towards the opposite elbow.",
    },
    {
        id: 120,
        name: "Plank with Row",
        type: "core",
        sets: "3",
        reps: "10-15",
        difficulty: "intermediate",
        flavor: "unilateral",
        description:
            "Performing a dumbbell row from a plank position, requiring immense core stability.",
    },
    {
        id: 121,
        name: "Plank with Weight Transfer",
        type: "core",
        sets: "3",
        reps: "30-60s",
        difficulty: "intermediate",
        flavor: "unilateral",
        description: "Placeholder description.",
    },
    {
        id: 122,
        name: "Side Bridge and Reach",
        type: "core",
        sets: "3",
        reps: "10-15",
        difficulty: "intermediate",
        flavor: "unilateral",
        description:
            "A side plank with a 'thread the needle' reach-through motion.",
    },
    {
        id: 123,
        name: "Core Row",
        type: "core",
        sets: "3",
        reps: "10-15",
        difficulty: "intermediate",
        flavor: "unilateral",
        description: "Placeholder description.",
    },
    {
        id: 124,
        name: "T-Push and Hold",
        type: "core",
        sets: "3",
        reps: "10-15",
        difficulty: "intermediate",
        flavor: "unilateral",
        description: "Placeholder description.",
    },
    {
        id: 125,
        name: "Barbell Rollout",
        type: "core",
        sets: "3",
        reps: "10-15",
        difficulty: "advanced",
        flavor: "bilateral",
        description:
            "An advanced core exercise, rolling a barbell out from a kneeling position.",
    },
];
